# Generated by Django 3.1.2 on 2021-07-07 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210706_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='phone_numder',
            field=models.CharField(default='5', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.department'),
        ),
    ]
