# Generated by Django 3.2.5 on 2021-08-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_doctor_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='additiona_information',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(choices=[('I положительная', '1+'), ('I отрицательная', '1-'), ('II положительная', '2+'), ('II отрицательная', '2-'), ('III положительная', '3+'), ('III отрицательная', '3-'), ('IV положительная', '4+'), ('IV отрицательная', '4-')], max_length=17),
        ),
    ]
