# Generated by Django 3.2.5 on 2021-08-13 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210810_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='symptoms',
        ),
        migrations.DeleteModel(
            name='Symptom',
        ),
    ]
