# Generated by Django 3.2.5 on 2021-08-25 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_reference_lenght'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.department'),
        ),
    ]
