# Generated by Django 3.1.2 on 2021-05-22 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210522_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.folder'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='above_folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.folder'),
        ),
    ]
