# Generated by Django 3.1.2 on 2021-05-26 04:40

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210522_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='slug',
            field=models.SlugField(auto_created=True, default='defoult'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=main.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.folder'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='above_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.folder'),
        ),
    ]
