# Generated by Django 3.1.2 on 2021-05-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210526_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='slug',
            field=models.SlugField(default='defoult'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repository',
            name='slug',
            field=models.SlugField(default='defoult'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='slug',
            field=models.SlugField(),
        ),
    ]
