# Generated by Django 3.1.2 on 2021-05-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210526_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='slug',
        ),
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default='def'),
            preserve_default=False,
        ),
    ]
