# Generated by Django 3.1.2 on 2021-06-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210528_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='is_private',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
