# Generated by Django 3.1.2 on 2021-03-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210307_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicon',
            name='dollar',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='politicon',
            name='euro',
            field=models.CharField(max_length=20),
        ),
    ]
