# Generated by Django 3.1.2 on 2021-03-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210307_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicon',
            name='oil',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
