# Generated by Django 3.1.2 on 2021-03-07 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politicon',
            name='weather',
        ),
    ]
