# Generated by Django 3.1.2 on 2021-03-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210325_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, help_text='Аватар', upload_to='images/profile/%Y/%m/%d', verbose_name='Ссылка картинки'),
        ),
    ]
