# Generated by Django 3.1.2 on 2021-03-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='messange',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
