# Generated by Django 3.1.2 on 2021-03-30 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_messange_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messange',
            name='addressee_group',
        ),
        migrations.AlterField(
            model_name='messange',
            name='addressee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Адресат', to='main.profile'),
        ),
        migrations.CreateModel(
            name='MessangeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('addressee_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.group')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profile')),
            ],
        ),
    ]
