# Generated by Django 3.1.2 on 2021-04-08 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_group_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messange',
            name='addressee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adress', to='main.profile'),
        ),
    ]
