# Generated by Django 3.1.2 on 2021-05-09 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210509_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messange',
            old_name='date',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='messangegroup',
            old_name='date',
            new_name='pub_date',
        ),
    ]
