# Generated by Django 3.1.2 on 2021-07-06 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='reference',
            name='next_doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_doctor', to='main.doctor'),
        ),
        migrations.DeleteModel(
            name='Symptoms',
        ),
        migrations.AddField(
            model_name='reference',
            name='symptoms',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.symptom'),
        ),
    ]
