# Generated by Django 3.1.2 on 2021-07-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210707_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(default='password', max_length=70),
            preserve_default=False,
        ),
    ]
