# Generated by Django 3.1.2 on 2021-01-02 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='number_of_comments',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='number_of_pingbacks',
        ),
    ]
