# Generated by Django 3.1.2 on 2021-01-02 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210102_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='mod_date',
        ),
    ]
