# Generated by Django 3.1.2 on 2021-01-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_entry_mod_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='rating',
        ),
        migrations.AddField(
            model_name='entry',
            name='dizlike',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='like',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
