# Generated by Django 3.1.2 on 2021-01-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210103_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('passvord', models.CharField(max_length=13)),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='passvord',
            field=models.CharField(default=4, max_length=13),
            preserve_default=False,
        ),
    ]
