# Generated by Django 3.1.2 on 2021-01-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210103_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField()),
                ('author', models.ManyToManyField(to='main.User')),
                ('post', models.ManyToManyField(to='main.Entry')),
            ],
        ),
    ]
