# Generated by Django 3.1.2 on 2021-01-05 06:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_vie',
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
