# Generated by Django 3.1.2 on 2021-01-05 06:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_auto_20210105_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='passvord',
        ),
        migrations.RemoveField(
            model_name='user_vie',
            name='passvord',
        ),
        migrations.AddField(
            model_name='author',
            name='user_main',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user_vie',
            name='user_main',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
