# Generated by Django 3.1.2 on 2021-01-08 11:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_auto_20210108_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dizlikeq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('post', models.ManyToManyField(to='main.Entry')),
            ],
        ),
        migrations.CreateModel(
            name='Likeq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('post', models.ManyToManyField(to='main.Entry')),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
