# Generated by Django 3.1.2 on 2021-01-12 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210108_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='email',
        ),
        migrations.RemoveField(
            model_name='author',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user_vie',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user_vie',
            name='name',
        ),
    ]
