# Generated by Django 3.1.2 on 2021-01-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210112_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author_blog',
            field=models.ManyToManyField(to='main.Author'),
        ),
    ]
