# Generated by Django 3.1.2 on 2021-01-15 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_blog_author_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='dizlike',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='like',
        ),
    ]
